public class MyTest {
    public static void main(String[] args) {
        Compression kompresja = new Compression();
        // "001 001 001 010 111 011 001 001 110 000 001 001 001 001"
        kompresja.addWord("111010");
        kompresja.addWord("100100");
        kompresja.addWord("111010");
        kompresja.addWord("110101");
        kompresja.addWord("111100");
        kompresja.addWord("111011");
        kompresja.addWord("101101");
        kompresja.addWord("111111");
        kompresja.addWord("111111");
        kompresja.addWord("111111");
        kompresja.addWord("111101");
        kompresja.addWord("111111");
        kompresja.addWord("111010");
        kompresja.addWord("110100");
        kompresja.addWord("111101");
        kompresja.addWord("111110");
        kompresja.addWord("101101");
        kompresja.addWord("110011");
        kompresja.addWord("111011");
        kompresja.addWord("111100");
        kompresja.addWord("110010");
        kompresja.addWord("111001");
        kompresja.addWord("111011");
        kompresja.addWord("111011");
        kompresja.addWord("111010");
        kompresja.addWord("111101");
        kompresja.addWord("111101");
        kompresja.addWord("111010");
        kompresja.compress();
        System.out.println(kompresja.getHeader());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        System.out.println(kompresja.getWord());
        // kompresja.addWord("101");
        // kompresja.addWord("110");
        // kompresja.addWord("111");
        // kompresja.addWord("111");
        // kompresja.addWord("111");
        // kompresja.addWord("110");
        // kompresja.addWord("111");
        // kompresja.addWord("111");
        // kompresja.addWord("110");
        // kompresja.addWord("111");
        // kompresja.addWord("111");
        // kompresja.addWord("110");
        // kompresja.addWord("101");
        // kompresja.addWord("110");
        // kompresja.addWord("101");
        // kompresja.addWord("111");
        // kompresja.addWord("111");
        // kompresja.addWord("111");
        // kompresja.compress();
        // System.out.println(kompresja.getHeader());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
        // System.out.println(kompresja.getWord());
    }
}
